### PR TITLE
Add Wrtiable facade to LargeText to enable file editing

### PR DESCRIPTION
**Pull request by Groostav**
Hey @fge,

Big fan of the library, I've used it on our current project to scan some really large files and generate a set of Ranges that contain interesting things in the file.

Now I need to change those ranges and write them back. The purpose of this proposed work is to write content back to files.

This particular pull request contains nothing except an outline for how I plan to implement this feature. I do not have a test plan for you, but I will likely TDD this issue from this point so hopefully that will satisfy any testing requirements you would have. 

A few more details here:
http://stackoverflow.com/questions/36072767/how-to-modify-update-a-large-file-with-small-content-changes-at-specific-indexes

Specifically you can imagine the case where we have a file like this:

```
          ***** ANSYS ANALYSIS DEFINITION (PREP7) *****

 ELEMENT TYPE      1 IS SHELL63      ELASTIC SHELL               
  KEYOPT( 1- 6)=        0      0      0        0      0      0
  KEYOPT( 7-12)=        0      0      0        0      0      0
  KEYOPT(13-18)=        0      0      0        0      0      0

 CURRENT NODAL DOF SET IS  UX    UY    UZ    ROTX  ROTY  ROTZ
  THREE-DIMENSIONAL MODEL

 REAL CONSTANT SET       1  ITEMS   1 TO   6
   0.10000E-02  0.10000E-02  0.10000E-02  0.10000E-02   0.0000       0.0000    

 REAL CONSTANT SET       1  ITEMS   7 TO  12
    0.0000       0.0000       0.0000       0.0000       0.0000       0.0000    

 REAL CONSTANT SET       1  ITEMS  13 TO  18
    0.0000       0.0000       0.0000       0.0000       0.0000       0.0000    

 REAL CONSTANT SET       1  ITEMS  19 TO  24
    0.0000       0.0000       0.0000       0.0000       0.0000       0.0000    

 TEMPERATURE TABLE ERASED.

 *** PROPERTY TEMPERATURE TABLE    NUM. TEMPS=  1 ***
 SLOC=   1     0.000000    

 PROPERTY TABLE EX    MAT=      1  NUM. POINTS=  1
 SLOC=   1    0.2620005E+09

 PROPERTY TABLE PRXY  MAT=      1  NUM. POINTS=  1
 SLOC=   1    0.3000000    
```

you can imagine that the value on the 4th line from the bottom, `0.2620005E+09` is of some domain interest to us, but we also need the ability to create an _identical file_ with a new value say `0.5432100E+08` at that location. To do that, I really want largeText to provide me with an API to write changes through to a file.

This outlined work assumes that you will make many small changes to a single large file. The small changes themselves will not consume a problematic amount of memory. The source file is still assumed to be large, which means effective handling of file streams to achieve maximum performance is very much desired.

Given your blessing, I'll implement this and hopfully open a pull request on the weekend sometime.

Thanks for reading!

-Geoff

### CODE REVIEW

**Comment by fge** [comment]
Hello,

First of all, thanks a lot for finding this library useful! However, there's a catch in your proposal; generally, it is never a good idea to modify text files inline, since writes to the final content may fail, and you would end up with a corrupt file.

This means that such an API you envison would need to write the updated contents to a _new file_ and replace those contents on the original file when done. Something like:

``` java
try (
    final MutableCharSequence mcs = ....;
) {
    // work with mcs
}
```

and have that MutableCharSequence handle the replacement of the original file when done.

To be honest, I'm really not sure about the use case at the moment. I'll try and reread your original proposal again. But inline modifications of files is one thing that should never be done in practice, save for data which you know does not change size, even in the middle of a file; and this is not quite the case here.

**Comment by Groostav** [comment]
> But inline modifications of files is one thing that should never be done in practice, save for data which you know does not change size, even in the middle of a file; and this is not quite the case here.

Why so?

I agree its a bit of nuisance but 'never do this in practice' seems kind've hard-lined. 

The problem I have is that we need to read & update documents of arbitrary grammers. The above text is an output report from one of the more popular engineering suites out there called [ANSYS mechanical](http://www.ansys.com/Products/Structures/ANSYS-Mechanical-Enterprise), and despite searching high and low, speaking to people at ANSYS itself and its consultancies, I cannot find a formal grammar for the document you see above. Even if I did come up with something, I would have to repeat the process for every different tool our users want to use with our software --many of which we might not even be aware of. We might well undertake this task if we can drum up enough sales; if the ranorex guys can support as many UI frameworks as they do surely we can integrate with a few dozen API's and write custom scanners for a few dozen different document formats, but from a minimum-viable-product mode, and while we're still very much a start-up, I dont know that I can manage that.

Unfortunately, as a lowest common denominator solution I'm left parsing and updating text files of arbitrary formats. To search for text I've employed a fairly traditional row-column style text search with LargeText, and I'm happy with that, but given a particular row-column value (translated into a character index by our code + LargeText), and a need to write a value to that location in the file, I'm not sure what else I can do.

I'm also not too sure what implementing `Closable` (for use in the try-with-resources above) gets me here. Probably I'd attempt to hide that from callers inside a try-finally block (or try-with-resources block) in the write functions themselves, since I don't think this object would expose any methods that interact with it while its writing, so I think that exposing the object mid-write to the caller isn't a good idea. 

I am well acquainted with the need to protect users from corrupt files though, so I will absolutely leverage a write-to-different-file-then-swap-inode-entries style of update. I'm not sure if the [`Files.move`](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#move%28java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...%29) method is atom

I could also return a `Promise` (which wasn't introduced with `Future` in j.u.concurrent, so maybe a `Future<Void>`?) to make this asynchronous, in the name of keeping with the parallel nature of the read methods on `LargeText`.

**Comment by fge** [comment]
> Why so?
> 
> I agree its a bit of nuisance but 'never do this in practice' seems kind've hard-lined.

It is, however, the truth.

Consider multibyte encodings (and that includes UTF-8); consider replacing one code point by another in the middle of a file and the replacement code point results in a wider byte array than the previous one.

This is why modifying text files inline is never a good idea. There is just no justification in doing that. The solution is, and always will be, to write the updated contents to a new file and replace the original file once it is assured that the new file is safely written.

Again, this is the only viable way of doing this. Any other way can lead to potential corruption of the file's contents, and nobody wants that.

As to `Files.move()`, it is atomic. Especially if you specify to `StandardCopyOption.ATOMIC_MOVE`; if this is not supported, fall back to `StandardCopyOption.REPLACE_EXISTING`.

**Comment by fge** [comment]
Also, you are talking about parsing files... Well, maybe you want to look at the work currently ongoing with [grappa](https://github.com/fge/grappa).

**Comment by Groostav** [comment]
Ahh I see, @fge,

I am not looking to implement an "in-line" solution like the one in [RandomAccessFile](https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html). I have no intention of doing an in-place write quite like that. I was planning on using `FileChannel.TransferFrom()` 'block by block' into a new file on the same drive, and then simply renaming or moving the new file to the name of the old one, deleting the existing file (if necessary).

But outside of that, there is one problem with what I'm suggesting:

I'm assuming that the user is making relatively small changes to a relatively large file. I can pay some attention to ensure that I'm only using `CharSequence`s, for those presumed-small replacement sequences, but if you wanted to perform an operation like take one large file, cut it in half, and insert another large file between the two portions of the other large file, this likely wont let you do it. While that particular circumstance might be easily solved by manually manipulating FileChannels, in the case where you want to create a number of 'stripes' from one large file into another --a use case that LargeText's reading funcitonality would be good at reading for--, my planned implementation is likely to get you into trouble.

I've been spending a fair bit of time with the functional programming community lately, and it seems to me that what I'm looking to do is [`zip`](https://msdn.microsoft.com/en-us/library/dd267698%28v=vs.100%29.aspx) on two large files, divided by indicies. I wonder if I can change this to more closely reflect that.

That said, if this conversation bores you and/or you don't think this would be a valuable addition to your library, I can take this work and just make it part of my project's repo.

**Comment by Groostav** [comment]
I'll take this offline, since there are a number of things that need to be done. If your interested we can merge it in, if you think it might be useful but dont want it on your library I can come up with my own repo that declares yours as a dependency, and if you dont like it and dont think its useful, I'll keep it internal tot he project im working on.

cheers!

-Geoff

**Pull request closed without merging**
